spring:
  mail:
    host: smtp.163.com
    username: jocularchao@163.com
    password: CZNYVRKNJMJOVXNG
  rabbitmq:
    addresses: localhost
    username: community_admin
    password: community_admin
    virtual-host: /template
  security:
    filter:
      order: -100
    jwt:
      key: abcdefghijk
      expire: 7
  data:
    redis:
      database: 1
      host: 127.0.0.1
      port: 6379
  datasource:
    url: jdbc:mysql://localhost:3306/community
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
